### PR TITLE
Update feedparser to 6.0.2 and code formatting

### PR DESCRIPTION
**Pull request by yuvalabou**
- Format the code using black, and remove logger as it hasn't been used
- update feedparser to 6.0.2
- Use SensorEntity
- Check with hassfest

### CODE REVIEW

**Comment by iantrich** [comment]
awesome! Thanks!

**Comment by yuvalabou** [comment]
As stated in issue #36 this change will require HA version 2021.4 as it introduces the new SensorEntity.
My bad.

**Comment by iantrich** [comment]
I think you can add a required version in HACS or perhaps the manifest. I'll look tonight

**Comment by iantrich** [comment]
Delete 0.1.3 and created release 0.1.4 which require 2021.4

**Pull request merged**
